Birthdate:
  cde: Birthdate
  columns:
    pid: pid
    uniqid: uniqid
    valueOutput_date: birthdate

Sex:
  cde: Sex
  columns:
    pid: pid
    uniqid: uniqid
    valueAttributeIRI: sexURI
    valueOutput_string: sexLabel

Status:
  cde: Status
  columns:
    pid: pid
    uniqid: uniqid
    valueOutput_string: status label
    valueAttributeIRI: status_uri
    startdate: date
    enddate: date

Date_of_death:
  cde: Date_of_death
  columns:
    pid: pid
    uniqid: uniqid
    valueOutput_date: death_date
    startdate: date
    enddate: date

Care_pathway:
  cde: Care_pathway
  columns:
    pid: pid
    uniqid: uniqid
    valueOutput_date: first_visit_date
    startdate: first_visit_date
    enddate: first_visit_date
    
Diagnosis:
  cde: Diagnosis
  columns:
    pid: pid
    uniqid: uniqid
    valueAttributeIRI: ordo_uri
    valueOutput_string: diagnostic_opinion
    startdate: date
    enddate: date

Date_of_diagnosis:
  cde: Onset_diagnosis
  columns:
    pid: pid
    uniqid: uniqid
    valueOutput_date: diagnosis_date
    valueAttributeIRI: diagnosis_uri
    startdate: diagnosis_date
    enddate: diagnosis_date

Date_of_symptoms:
  cde: Onset_symptoms
  columns:
    pid: pid
    uniqid: uniqid
    valueAttributeIRI: onset_uri
    valueOutput_date: onset_date
    startdate: onset_date
    enddate: onset_date

Genotype_HGVS:
  cde: Genotype_HGVS
  columns:
    pid: pat_id
    valueOutput_string: hgvs_code
    valueAttributeIRI: clinvar_uri

Genotype_OMIM:
  cde: Genotype_OMIM
  columns:
    pid: pid
    uniqid: uniqid
    valueAttributeIRI: omim_uri

Genotype_HGNC:
  cde: Genotype_HGNC
  columns:
    pid: pid
    uniqid: uniqid
    valueAttributeIRI: hgnc_code 
    
Phenotype:
  cde: Phenotype
  columns:
    pid: pid
    uniqid: uniqid
    valueAttributeIRI: HP_IRI
    valueOutput_string: HP_Label
    startdate: date
    enddate: date

Consent:
  cde: Consent
  columns:
    pid: pid
    uniqid: uniqid
    valueOutput_string: result_label
    outputURI: result_uri
    startdate: date
    enddate: date

Disability:
  cde: Disability
  columns:
    pid: pid
    uniqid: uniqid
    processURI: test_uri
    valueOutput_float: score
    startdate: test_date
    enddate: test_date
    