prefixes:
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  ex: http://ejp-rd.eu/ids/
  obo: http://purl.obolibrary.org/obo/
  this: http://duchenne.nl/dpp/participants/ 
  sio: https://semanticscience.org/resource/
  vocab: https://ejp-rd.eu/vocab/
  pico: http://data.cochrane.org/ontologies/pico/
  ndfrt: http://purl.bioontology.org/ontology/NDFRT/
  
sources:
  height-source:
    access: |||DATA|||
    referenceFormulation: |||FORMULATION|||
    iterator: $  

mappings:

  identifier_has_value: 
    sources: 
      - height-source 
    s: this:individual_$(pid)_$(uniqid)#ID 
    po: 
      - [sio:has-value, $(pid)]
      
  identifier_denotes: 
    sources: 
      - height-source 
    s: this:individual_$(pid)_$(uniqid)#ID 
    po: 
      - predicates: a 
        objects: 
            value: https://ejp-rd.eu/vocab/identifier 
            type: iri 
      - predicates: sio:denotes 
        objects: 
            value: this:individual_$(pid)_$(uniqid)#patientRole 
            type: iri 

  person_has_role: 
    sources: 
      - height-source 
    s: this:individual_$(pid)#Person 
    po: 
      - predicates: a 
        objects: 
            value: https://ejp-rd.eu/vocab/Person
            type: iri 
      - predicates: sio:has-role 
        objects: 
            value: this:individual_$(pid)_$(uniqid)#patientRole
            type: iri 

  patientRole_annotation: 
    sources: 
      - height-source 
    s: this:individual_$(pid)_$(uniqid)#patientRole 
    po: 
      - [a, obo:OBI_0000093] 
      - [rdfs:label, "Patient"] 




# Role in Process
       
  role_realized_proces:
    sources:
      - height-source
    s: this:individual_$(pid)_$(uniqid)#patientRole
    po:
      - predicates: sio:is-realized-in
        objects:
            value:  this:individual_$(pid)_$(uniqid)#height_measurement_Process
            type: iri

  process_annotation:
    sources:
      - height-source
    s: this:individual_$(pid)_$(uniqid)#height_measurement_Process
    po:
      - predicates: rdf:type
        objects:
            value:  $(processURI)
            type: iri
      - predicates: rdfs:label
        objects:
            value:  $(processLabel)
            datatype: xsd:string
      - predicates: sio:start-time
        objects:
            value:  $(date)
            datatype: xsd:dateTime
            
            
# Person has Quality
  person_has_quality:
    sources:
      - height-source
    s: this:individual_$(pid)#Person
    po:
      - predicates: sio:has-quality
        objects:
            value:  this:individual__$(pid)_$(uniqid)#height_Quality
            type: iri

  quality_annotation:
    sources:
      - height-source
    s: this:individual__$(pid)_$(uniqid)#height_Quality
    po:
      - predicates: rdf:type
        objects:
            value:  $(qualityURI)
            type: iri
      - predicates: rdfs:label
        objects:
            value:  $(qualityLabel)
            datatype: xsd:string


# quality basisfor meas

  quality_basis_for_meas:
    sources:
      - height-source
    s: this:individual__$(pid)_$(uniqid)#height_Quality
    po:
      - predicates: sio:is-basis-for
        objects:
            value:  this:individual__$(pid)_$(uniqid)#height_MeasVal
            type: iri


# Process has Output

  process_has_output:
    sources:
      - height-source
    s: this:individual_$(pid)_$(uniqid)#height_measurement_Process
    po:
      - predicates: sio:has-output
        objects:
            value:  this:individual__$(pid)_$(uniqid)#height_MeasVal
            type: iri



  measval_value:
    sources:
      - height-source
    s: this:individual__$(pid)_$(uniqid)#height_MeasVal
    po:
      - predicates: rdf:type
        objects:
            value:  sio:measurement-value
            type: iri
      - predicates: rdf:type
        objects:
            value:  $(measurementURI)
            type: iri
      - predicates: rdfs:label
        objects:
            value:  $(measurementLabel)
            datatype: xsd:string
      - predicates: sio:has-value
        objects:
            value:  $(height)
            datatype: xsd:float
      - predicates: rdfs:comment
        objects:
            value:  $(comments)
            datatype: xsd:string

  height_hasunit_unit:
    sources: 
      - height-source 
    s: this:individual__$(pid)_$(uniqid)#height_MeasVal
    po: 
      - predicates: sio:has-unit
        objects: 
            value: this:individual__$(pid)_$(uniqid)#height_MeasVal_unit
            type: iri

  unit_annotation:
    sources: 
      - height-source 
    s: this:individual__$(pid)_$(uniqid)#height_MeasVal_unit
    po: 
      - predicates: rdf:type
        objects: 
            value: http://purl.obolibrary.org/obo/UO_0000015
            type: iri
      - predicates: rdfs:label
        objects: 
            value: "centimeter"
            datatype: xsd:string
