prefixes:
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  ex: http://ejp-rd.eu/ids/
  obo: http://purl.obolibrary.org/obo/
  this: http://duchenne.nl/dpp/participants/ 
  sio: https://semanticscience.org/resource/
  vocab: https://ejp-rd.eu/vocab/
  pico: http://data.cochrane.org/ontologies/pico/
  ndfrt: http://purl.bioontology.org/ontology/NDFRT/
  
sources:
  personal-source:
    access: |||DATA|||
    referenceFormulation: |||FORMULATION|||
    iterator: $  

mappings:

  identifier_has_value: 
    sources: 
      - personal-source 
    s: this:individual_$(pid)_$(uniqid)#ID 
    po: 
      - [sio:has-value, $(pid)]
      
  identifier_denotes: 
    sources: 
      - personal-source 
    s: this:individual_$(pid)_$(uniqid)#ID 
    po: 
      - predicates: a 
        objects: 
            value: https://ejp-rd.eu/vocab/identifier 
            type: iri 
      - predicates: sio:denotes 
        objects: 
            value: this:individual_$(pid)_$(uniqid)#patientRole 
            type: iri 

  person_has_role: 
    sources: 
      - personal-source 
    s: this:individual_$(pid)#Person 
    po: 
      - predicates: a 
        objects: 
            value: https://ejp-rd.eu/vocab/Person
            type: iri 
      - predicates: sio:has-role 
        objects: 
            value: this:individual_$(pid)_$(uniqid)#patientRole
            type: iri 

  patientRole_annotation: 
    sources: 
      - personal-source 
    s: this:individual_$(pid)_$(uniqid)#patientRole 
    po: 
      - [a, obo:OBI_0000093] 
      - [rdfs:label, "Patient"] 




# Role in BIRTHDATE Process
       
  role_realized_birthdate_proces:
    sources:
      - personal-source
    s: this:individual_$(pid)_$(uniqid)#patientRole
    po:
      - predicates: sio:is-realized-in
        objects:
            value:  this:individual_$(pid)_$(uniqid)#birthdate_measurement_Process
            type: iri

  birthdate_process_annotation:
    sources:
      - personal-source
    s: this:individual_$(pid)_$(uniqid)#birthdate_measurement_Process
    po:
      - predicates: rdf:type
        objects:
            value:  $(processURI)
            type: iri
      - predicates: rdfs:label
        objects:
            value:  $(processLabel)
            datatype: xsd:string
            

# Person has Quality
  person_has_birthdate_quality:
    sources:
      - personal-source
    s: this:individual_$(pid)#Person
    po:
      - predicates: sio:has-quality
        objects:
            value:  this:individual__$(pid)_$(uniqid)#birthdate_Quality
            type: iri

  birthdate_quality_annotation:
    sources:
      - personal-source
    s: this:individual__$(pid)_$(uniqid)#birthdate_Quality
    po:
      - predicates: rdf:type
        objects:
            value:  $(birthdateQualityURI)
            type: iri
      - predicates: rdfs:label
        objects:
            value:  $(birthdateQualityLabel)
            datatype: xsd:string




# Process has Output

  birthdate_process_has_output:
    sources:
      - personal-source
    s: this:individual_$(pid)_$(uniqid)#birthdate_measurement_Process
    po:
      - predicates: sio:has-output
        objects:
            value:  this:individual__$(pid)_$(uniqid)#birthdate_MeasVal
            type: iri


  birthdate_quality_basis_for_meas:
    sources:
      - personal-source
    s: this:individual__$(pid)_$(uniqid)#birthdate_Quality
    po:
      - predicates: sio:is-basis-for
        objects:
            value:  this:individual__$(pid)_$(uniqid)#birthdate_MeasVal
            type: iri

  birthdate_measval_value:
    sources:
      - personal-source
    s: this:individual__$(pid)_$(uniqid)#birthdate_MeasVal
    po:
      - predicates: rdf:type
        objects:
            value:  sio:measurement-value
            type: iri
      - predicates: rdf:type
        objects:
            value:  $(measurementURI)
            type: iri
      - predicates: rdfs:label
        objects:
            value:  $(birthdate)
            datatype: xsd:string
      - predicates: sio:has-value
        objects:
            value:  $(birthdate)
            datatype: xsd:dateTime







# Role in GENDER Process
       
  role_realized_gender_proces:
    sources:
      - personal-source
    s: this:individual_$(pid)_$(uniqid)#patientRole
    po:
      - predicates: sio:is-realized-in
        objects:
            value:  this:individual_$(pid)_$(uniqid)#gender_measurement_Process
            type: iri

  gender_process_annotation:
    sources:
      - personal-source
    s: this:individual_$(pid)_$(uniqid)#gender_measurement_Process
    po:
      - predicates: rdf:type
        objects:
            value:  $(processURI)
            type: iri
      - predicates: rdfs:label
        objects:
            value:  $(processLabel)
            datatype: xsd:string
            
            
# Person has Quality
  person_has_gender_quality:
    sources:
      - personal-source
    s: this:individual_$(pid)#Person
    po:
      - predicates: sio:has-quality
        objects:
            value:  this:individual__$(pid)_$(uniqid)#gender_Quality
            type: iri

  gender_quality_annotation:
    sources:
      - personal-source
    s: this:individual__$(pid)_$(uniqid)#gender_Quality
    po:
      - predicates: rdf:type
        objects:
            value:  $(genderQualityURI)
            type: iri
      - predicates: rdfs:label
        objects:
            value:  $(genderQualityLabel)
            datatype: xsd:string


# Process has Output

  gender_process_has_output:
    sources:
      - personal-source
    s: this:individual_$(pid)_$(uniqid)#gender_measurement_Process
    po:
      - predicates: sio:has-output
        objects:
            value:  this:individual__$(pid)_$(uniqid)#gender_MeasVal
            type: iri


  gender_quality_basis_for_meas:
    sources:
      - personal-source
    s: this:individual__$(pid)_$(uniqid)#gender_Quality
    po:
      - predicates: sio:is-basis-for
        objects:
            value:  this:individual__$(pid)_$(uniqid)#gender_MeasVal
            type: iri

  gender_measval_value:
    sources:
      - personal-source
    s: this:individual__$(pid)_$(uniqid)#gender_MeasVal
    po:
      - predicates: rdf:type
        objects:
            value:  sio:measurement-value
            type: iri
      - predicates: rdf:type
        objects:
            value:  $(genderURI)
            type: iri
      - predicates: rdfs:label
        objects:
            value:  $(genderLabel)
            datatype: xsd:string
      - predicates: sio:has-value
        objects:
            value:  $(genderLabel)
            datatype: xsd:string
