version: "3"
services:

# if you are already running Rajaram's GraphDB image, then don't execute this portion
# the other portions will connect to Rajaram's GraphDB network
#  graphdb:
#    image: graph-db:9.7.0
#    restart: always
#    hostname: graphdb
#    ports:
#      - 7200:7200
#    volumes:
#      - graphdb-data:/opt/graphdb/home
#    networks:
#      - default
      #- bootstrap_graphdb_net 


# note that if you have not set-up specific security on graphdb,
# you do not need to set the environment, but it also does no harm.
# We recommend using a .env file in this folder to set your environment
  cde-box-daemon: 
    image: markw/cde-box-daemon:latest
    container_name: cde-box-daemon
    environment:
      GraphDB_User: ${GraphDB_User}
      GraphDB_Pass: ${GraphDB_Pass}
      baseURI: ${baseURI}
    depends_on:
      - yarrrml_transform
      - rdfizer
      - graphdb
    ports:
      - 4567:4567
    volumes:
        - ./data:/data
        - ./config:/config
    networks:
      - default
      - graphdb_net 
        
 
  updater:
    image: markw/fdp-metadata-updater:0.0.1
    restart: always
    hostname: updater
    depends_on:
      - graphdb
    environment:
      DATA_SPARQL_ENDPOINT: ${DATA_SPARQL_ENDPOINT}
      DIST_RECORDID: ${DIST_RECORDID}
      DATASET_RECORDID: ${DATASET_RECORDID}
      DOMAIN: ${DOMAIN}
      FDP_USERNAME: ${FDP_USERNAME}
      FDP_PASSWORD: ${FDP_PASSWORD}
       
  yarrrml_transform: 
    image: markw/yarrrml-parser-ejp:latest
    container_name: yarrrml_transform
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data
    networks:
      - default
      - graphdb_net 
  
  
  rdfizer: 
    image: markw/sdmrdfizer_ejp:0.1.0
    container_name: rdfizer
    ports:
      - "4000:4000"
    volumes:
      - ./data:/data
      - ./config:/config
    networks:
      - default
      - graphdb_net 

    
volumes:
  graphdb-data:
    external: true

    networks:
      - default
      - graphdb_net 
        
# Define networks here (this is the name of rajaram's bootstrap network)
networks:
  graphdb_net:
    external: true
